version: 2.1
workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: plugins/git
    steps:
      - run:
          name: install bash
          command: apk add bash
      - checkout
      - run:
          name: install tools
          command: bash ci/install-tools.sh
      - run:
          name: update pr
          command: bash ci/update-pr.sh
      - run:
          name: merge master
          command: bash ci/merge-master.sh
      - run:
          name: hello
          command: bash ci/hello.sh
